# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
#ZSH_THEME="tjkirch"
ZSH_THEME="dstj"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment one of the following lines to change the auto-update behavior
# zstyle ':omz:update' mode disabled  # disable automatic updates
# zstyle ':omz:update' mode auto      # update automatically without asking
# zstyle ':omz:update' mode reminder  # just remind me to update when it's time

# Uncomment the following line to change how often to auto-update (in days).
# zstyle ':omz:update' frequency 13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# You can also set it to another string to have that shown instead of the default red dots.
# e.g. COMPLETION_WAITING_DOTS="%F{yellow}waiting...%f"
# Caution: this setting can cause issues with multiline prompts in zsh < 5.7.1 (see #5765)
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
zsh-syntax-highlighting
git
golang
rust
docker
kubectl
minikube
1password
zsh-autosuggestions
)

fpath=(
  $fpath
  /usr/local/share/zsh-completions
  /usr/local/share/zsh/site-functions
  /opt/homebrew/share/zsh/site-functions
)
source $ZSH/oh-my-zsh.sh

# User configuration
SAVEHIST=0
export LESSHISTFILE=-

# export MANPATH="/usr/local/man:$MANPATH"
export GOPATH="$HOME/.go"

# export PATH="$PATH"
export PATH="/opt/homebrew/bin:$PATH"
export PATH="$PATH:$GOPATH/bin"
export PATH="$PATH:$HOME/.cargo/bin"
export PATH="$PATH:$HOME/.krew/bin"

# You may need to manually set your language environment
export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
export EDITOR='vim'

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# User commands
function jtmux() {
	tmux new-session -d -c ~/Downloads
	tmux new-window -d -c ~/Workspace
	tmux new-window -d -c ~/Workspace
	tmux new-window -d -c ~/Workspace
	tmux new-window -d -c /tmp
	tmux attach
}

# manage ssh-agent and gpg-agent
eval `keychain --quiet --eval --inherit any-once`

export PATH=$PATH:$(go env GOPATH)/bin

# bun completions
[ -s "/Users/lido/.bun/_bun" ] && source "/Users/lido/.bun/_bun"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"
export PATH="$HOME/.bun/bin:$PATH"

# deploytool helper
tool() {
  # 在子 shell 裡切換目錄，避免改變你當前的工作目錄
  ( cd /Users/lido/Desktop/NotImportant/BitoProject/Golang/deploytool \
    && go run ./main.go "$@" )
}

# git alias func

function gcb(){
    local branch="$1"
    git checkout -b "$branch"
}

function gac(){
    local msg="$*"
    local branch_name=$(git symbolic-ref --short HEAD 2>/dev/null)

    if [ $? -ne 0 ]; then
        echo "Error: Not in a git repository or unable to determine the branch name."
        return 1
    fi

    # 使用正則表達式檢查分支名稱是否符合票號格式 (例如: PRO-xxxx)
    if [[ "$branch_name" =~ ^PRO-[^/]+ ]]; then
        # 提取票號部分
        local ticket_number=$(echo "$branch_name" | awk -F'/' '{print $1}')
        local commit_message="[$ticket_number] $msg"
    else
        # 非票號分支名稱，直接使用 msg 作為提交訊息
        local commit_message="$msg"
    fi

    # 調試輸出
    echo "Branch name: $branch_name"
    echo "Commit message: $commit_message"

    # 執行 Git 命令
    git add .
    git commit -m "$commit_message"
}
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
